### PR TITLE
Support for Aseag (Aachen, Germany)

### PR DESCRIPTION
**Pull request by aquac**
I hope this code is now in acceptable shape. If not, I would be glad to hear your feedback.
Thanks

### CODE REVIEW

**Comment by otsaloma** [comment]
Thanks, glad to get a new provider included. A couple changes needed:

* To be consistent with other providers, please change in the JSON file the name to "Aachen" and description to "ASEAG" (or "Aachener Straßenbahn und Energieversorgungs-AG (ASEAG)" if the full name is helpful).

* Like with the other providers, please add in the top docstring a link to the web page where the API is documented.

* `find_nearby_stops` should return a blank list, not a dictionary.

* Replace the color "#007ac9" with the ASEAG red "#bb0032". Maybe add the same color for lines too in `parsejson_find_lines`?

Otherwise, it looks fine. I'll test it when you have made these changes. The coding style and formatting are a bit off, but that I can quicker fix myself.

**Comment by aquac** [comment]
Thanks for your feedback! I just pushed an updated version. May I ask you to check it again whether all required changes are implemented? Thanks

**Comment by aquac** [comment]
P.S.: I consider it myself still WIP as I couldn't test the nearby feature yet (I'm not in aachen currently)

**Comment by otsaloma** [comment]
The nearby call can be tested with a simple script, proving the coordinates, e.g.

```python
#!/usr/bin/env python3
import pan, pprint
provider = pan.Provider("aseag")
stops = provider.find_nearby_stops(6.084, 50.775)
pprint.pprint(stops)
```

Put that in e.g. file `test_nearby.py` in the Pan Transit source root and run with `python3 test_nearby.py`. Based on a quick test with downtown coordinates, it seems to work as expected.

I'll test the whole thing over the weekend, do some cosmetic changes and check with you before merging.

**Comment by otsaloma** [comment]
I did some polish, broken apart to small commits for clarity. Based on quick testing it seemed to work fine. Please check that I didn't break anything, after that I'm ready to merge and make a release.

**Comment by aquac** [comment]
Thanks a lot!

I knew that my code was horrible, but (now seeing the changes you made) that it was _that_ horrible, I did not expect ;-)

It seems to work fine, but I have some questions (probably related to the fact that I just realized it for the first time)

- What does the color coding (red, yellow, blue) in the the departure list indicate?
- In the favorite list, only some favorites have a colored bar at the beginning. Does that mean anything special or why is that?
- The station description in the favorites (information which lines depart from there) seems to be based on the moment when the favorite was added and does not seem to be updated. Meaning, when e.g. a favorite was added on a Sunday lines that do not depart Sundays are not displayed there.
- If pan-transit is only running in the background (visible on home screen) it still pulls regularly for updates of the selected station, right? Is that also the case when the screen is off?

**Comment by otsaloma** [comment]
> What does the color coding (red, yellow, blue) in the the departure list indicate?

"color (optional) can be used to provide departure-specific colors, e.g. official colors for individual metro lines. If omitted, departures will be colored based on comparing the stop coordinates and the users position and calculating which departures the user cannot reach in time (red), which need fast walking or running (yellow) and which require no hurry (blue)."

> In the favorite list, only some favorites have a colored bar at the beginning. Does that mean anything special or why is that?

The ones that have a colored bar are near your current position. You can adjust the radius in the preferences dialog.

> The station description in the favorites (information which lines depart from there) seems to be based on the moment when the favorite was added and does not seem to be updated. Meaning, when e.g. a favorite was added on a Sunday lines that do not depart Sundays are not displayed there.

It's updated once a week, so it's designed to react to seasonal changes, but not to weekdays or hours.

> If pan-transit is only running in the background (visible on home screen) it still pulls regularly for updates of the selected station, right? Is that also the case when the screen is off?

Only when the cover is active, i.e. when you're looking at the home screen. If you're using another app or the phone is off, then it's not updated.

**Pull request merged**
